import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {RootLayoutComponent} from "./_layout-component";
import Head from "next/head";
import { Providers } from "./providers";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <Head>

      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    </Head>

    <body className={inter.className}>
      <Providers>
        <RootLayoutComponent>
          {children}
        </RootLayoutComponent>
      </Providers>
      </body>
  

  </html>
  );
}
